version: '3.7'
services:
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        restart: always
        depends_on:
            - wordpress
        ports:
            - 8443:443
        environment:
            SCHOOL_USERNAME: ${USER}
            NGINX_WORDPRESS_CONTAINER_NAME: ${NGINX_WORDPRESS_CONTAINER_NAME}
            NGINX_WORDPRESS_PORT: ${NGINX_WORDPRESS_PORT}
        networks:
            - inception-network
    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        restart: always
        expose:
            - 9000
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DB_HOST: ${MYSQL_DB_HOST}
        networks:
            - inception-network
    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        restart: always
        expose:
            - 3306
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        networks:
            - inception-network

networks:
    inception-network:
        driver: bridge
